### ISSUE TITLE
Crushing html produces unwanted "empty lines filled with whitespaces"

### ISSUE THREAD

**Issue by SylannBin** [codsen/codsen#5] opened 2021-03-26 22:01 UTC
**Package's name**
html-crush (4.1.4)

**Describe the situation**
Here is a Simple example to reproduce my problem. It should be self explanetory :)

```js
const { crush } = require("html-crush")

const input = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div>Hello</div>
</body>
</html>
`

const output = crush(input, {
  removeLineBreaks: true,
  removeIndentations: true,
  removeHTMLComments: true,
  removeCSSComments: true,
})

output.result === `<!DOCTYPE html>

<html lang="en">

<head>
  
<meta charset="UTF-8">
  
<meta http-equiv="X-UA-Compatible" content="IE=edge">
  
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  
<title>Document</title>

</head>

<body><div>Hello</div>

</body>

</html>
`
```

Is there something I'm doing wrong?

I would like the result to be compacted with no extra newlines/whitespaces, until the line length is reached...

**Comment by revelt** [comment] 2021-03-28 18:35
hi Romain,

Sorry for the bug. Were you using front-end (htmlcrush.com) or the npm package in a Node program?

I suspect it's the htmlcrush.com... If so, probably Windows line endings, CRLF... I use both front-end and npm package myself daily, in production, and I don't get the blank lines. But I'm on Mac so all my line endings are LF. But maybe it's something else...

I did beef up the `html-crush` algorithm this morning to retain CR or CRLF or LF line endings, but I didn't find any blank lines in unit tests. I even placed your snippet into [one test](https://github.com/codsen/codsen/blob/a6a993bc994a648083c2d66761e72a69b6ba5986/packages/html-crush/test/test.js#L1509). The only thing I noticed was v.4.1.4 turning some CRLF into LF (which should be fixed in v.4.1.5)...

Can you please check the latest front-end on https://htmlcrush.com on **v.4.1.5** (refresh if header shows older)?

I tried `input` HTML snippet as is, then with converted line endings to Windows CRLF — I can't recreate it. I don't get blank lines... But hopefully we can recreate this and solve.

Again, sorry for the trouble.

**Comment by SylannBin** [comment] 2021-03-30 12:06
Hi revelt,

I "originally" got the error using maizzle and then proceeded to do many tests.
I started in the node REPL and then continued with the script above.

**To clarify my method**

Having a file `test-crush.js` with the content below, here is what I get from a terminal (note I updated html-crush):

```sh
$ node -v
v15.12.0
$ node -e 'console.log(require("html-crush").version)'
4.1.5
$ node test-crush.js
true
```

```js
// test-crush.js
const { crush } = require("html-crush")

const input = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div>Hello</div>
</body>
</html>
`

const output = crush(input, {
  removeLineBreaks: true,
  removeIndentations: true,
  removeHTMLComments: true,
  removeCSSComments: true,
})

console.log(output.result === `<!DOCTYPE html>

<html lang="en">

<head>
  
<meta charset="UTF-8">
  
<meta http-equiv="X-UA-Compatible" content="IE=edge">
  
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  
<title>Document</title>

</head>

<body><div>Hello</div>

</body>

</html>
`)

```

**Comment by revelt** [comment] 2021-04-01 19:05
I think I found the source, the CJS build, during Rollup+Babel somehow omits the spread operator which changes the logic of the program. However, the ESM and UMD builds are fine! That threw me off track at the beginning... Only CJS, CommonJS builds are not working as intended. What's crazy is that it's a real bug somewhere in Babel, or rather its config... I'll nail this very soon.

@SylannBin, thank you for flagging this up! I'll write up an article what went wrong and publish and credit you for the find.

Again, sorry for the bug. 

It's a shitty situation, I did all my best, unit tests passed (on ESM), it's just Babel and/or Rollup produced a bad output which they should not have produced. But I'm "responsible" for the library in the end... Do you see? The bundlers should not even allow broken code, they should be smart-enough to alert us! Anyhow, I plan to release a patch this weekend.

Sorry about this.

**Comment by revelt** [comment] 2021-04-03 15:37
It should be fixed in 4.1.7 released an hour ago, please confirm

**Comment by SylannBin** [comment] 2021-04-03 20:55
Hi @revelt,

I confirm, it works!

Thank you very much for your quick intervention.

**Comment by revelt** [comment] 2021-04-03 21:47
@SylannBin thank you! Here's the writeup as promised, https://codsen.com/articles/html-crush-bug-fixed/ — closing

**Closed by revelt** 2021-04-03 21:47 UTC
